language: rust
install:
  - curl -O http://static.rust-lang.org/dist/rust-nightly-$ARCH-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-$ARCH-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-$ARCH-unknown-linux-gnu/ && sudo ./install.sh)
script:
  - make
  - make examples

env:
  - ARCH=i386 RUSTC='rustc --target=i686-unknown-linux-gnu' CC='cc -m32'
  - ARCH=x86_64
