[project]

name = "civet"
version = "0.1.0"
authors = ["wycats"]
build = "build.rs"

[dev-dependencies.route-recognizer]
git = "https://github.com/conduit-rust/route-recognizer.rs"

[dependencies.conduit]
git = "https://github.com/conduit-rust/conduit"

[dependencies.semver]
git = "https://github.com/rust-lang/semver"
